version: '3.8'
services:
  app:
    build: .
    container_name: moments
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prod.db
    ports:
      - '3000:3000'
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./prisma:/app/prisma