version: '3.8'
services:
  app:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=file:./prod.db
    command: sh -c "npm install && npm run build && npm start" 