version: '3.8'
services:
  app:
    build: .
    container_name: moments
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prod.db
    ports:
      - '3001:3000'
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./prisma:/app/prisma
    networks:
      - n8n-docker-caddy_default

networks:
  n8n-docker-caddy_default:
    external: true